### PR TITLE
Avoid blank pages, omit desc tab instead

### LINKED ISSUE #44: Avoid including erroneous packages in the bundle at built time
See #43 for details

### PR DESCRIPTION
**Pull request by arabello**
Closes #44

These changes allow packages with Markdown (README) serialization failures to show up in the web hub instead of having a blank page. ATM the description tab is simply omitted if a serialization error occurs. Additionally, a log error is added so we can better track which packages fails at build time. 

I also refactored some code to simplify stuff around the get static props by eliminating FP jargon. Moreover, if something brutal happens (eg. we get fetch the index) the entire build should fails to avoid deployment of a basically empty hub.

As a test, I took some packages listed in #43 and other discussions and check out locally that they show up in the web hub. 
- espanso-pinyin-tones
- vim-digraphs
- arrows
- portuguese-accents
- flutter-snippets
- tholzschuh-maths
- alt-codes
- med-expansions
- better-typography
- discord-snippets

Here's some screenshots
|  |  |
|----------|----------|
| Image 1 | Image 2 |
| Image 3 | Image 4 |

This table arranges the four images in a 2x2 grid, with two images in each row.

### CODE REVIEW

**Comment by arabello** [comment]
Oh, we could show the desc tab with a placeholder pointing to the Github repo (if available)

**Review by AucaCoyan — APPROVED** [review]
All good!

**Comment by AucaCoyan** [comment]
> Oh, we could show the desc tab with a placeholder pointing to the Github repo (if available)

Whatever suits you better. We can merge this as is and worry about that later, o make an extra push and resolve that. I'm happy with both!

**Comment by AucaCoyan** [comment]
Thank you!

**Pull request merged**
